version: '3.8'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    environment:
      TZ: UTC
      PGTZ: UTC
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
        HOST:                  $HOST
        API_PORT:              $API_PORT
        AWS_ACCESS_KEY_ID:     $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        DB_HOST:               $DB_HOST
        DB_NAME:               $DB_NAME
        DB_USERNAME:           $DB_USERNAME
        DB_PASSWORD:           $DB_PASSWORD
        S3_REGION:             $S3_REGION
        S3_BUCKET:             $S3_BUCKET
        RAILS_MASTER_KEY:      $RAILS_MASTER_KEY
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./api:/$WORKDIR
      - api-bundle:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        HOST:              $HOST
        FRONT_PORT:        $FRONT_PORT
        API_KEY:           $API_KEY
        AUTH_DOMAIN:       $AUTH_DOMAIN
        PROJECT_ID:        $PROJECT_ID
        DATABASE_URL:      $DATABASE_URL
        STORAGE_BUCKET:    $STORAGE_BUCKET
        MESSAGE_SENDER_ID: $MESSAGE_SENDER_ID
    command: yarn run dev
    volumes:
      - ./front:/$WORKDIR
      - front-node_modules:/app/node_modules
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api
volumes:
  mysql_data:
  api-bundle:
  front-node_modules: